"""initial schema (§5 data model)

Creates the full §5 schema from the SQLAlchemy metadata. Using metadata.create_all here
keeps this baseline migration guaranteed-consistent with the models; later phases use
normal autogenerated migrations on top of this revision.

Revision ID: 0001
Revises:
Create Date: 2026-06-19
"""
from typing import Sequence, Union

from alembic import op

# Import Base + register all models.
from backend.persistence.database import Base
from backend.persistence import models  # noqa: F401

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    Base.metadata.create_all(bind=op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(bind=op.get_bind())
